
const finGridData = 
    {
        name: 
        [
            "Activated down-regulation power (15min)",
            "Activated up-regulation power (15min)",
            "Automatic Frequency Restoration Reserve, activated, down (60min)",
            "Automatic Frequency Restoration Reserve, activated, up (60min)",
            "Automatic Frequency Restoration Reserve, capacity, down (60min)",
            "Automatic Frequency Restoration Reserve, capacity, up (60min)",
            "Automatic Frequency Restoration Reserve, price, down (60min)",
            "Automatic Frequency Restoration Reserve, price, up (60min)",
            "Balancing Capacity Market (mFRR), up, hourly market, price (60min)",
            "Balancing Capacity (mFRR), down, hourly market, bids (60min)",
            "Balancing Capacity (mFRR), down, hourly market, price (60min)",
            "Balancing Capacity (mFRR), down, hourly market, procured volume (60min)",
            "Balancing Capacity (mFRR), down, hourly market, procurement forecast (60min)",
            "Balancing Capacity (mFRR), hourly market, procurement from Estonia (60min)",
            "Balancing Capacity (mFRR), up, hourly market, bids (60min)",
            "Balancing Capacity (mFRR), up, hourly market, procurement forecast (60min)",
            "Balancing Capacity (mFRR), up, hourly market, procured volume (60min", 
            "Bilateral trade between FI-RUS (60min)",
            "Bilateral trade capacity FI-RUS (60min)",
            "Bilateral trade capacity RUS-FI (60min)",
            "Bilateral trade capacity FI-RUS, unused (60min)",
            "Bilateral trade capacity RUS-FI, unused (60min)",
            "Cogeneration of district heating - real time data (3min)",
            "Commercial transmission of electricity between FI-EE",
            "Commercial transmission of electricity between FI-SE1",
            "Commercial transmission of electricity between FI-SE3",
            "Cross-border transmission fee, export to Russia (60min)",
            "Cross-border transmission fee, import from Russia (60min)",
            "Day-ahead transmission capacity EE-FI - official (60min)",
            "Day-ahead transmission capacity FI-EE - official (60min)",
            "Day-ahead transmission capacity FI-SE1 - official (60min)",
            "Day-ahead transmission capacity FI-SE1 - planned (60min)",
            "Day-ahead transmission capacity FI-SE3 - official (60min)",
            "Day-ahead transmission capacity FI-SE3 - planned (60min)",
            "Day-ahead transmission capacity SE1-FI  - official (60min)",
            "Day-ahead transmission capacity SE1-FI - planned (60min)",
            "Day-ahead transmission capacity SE3-FI - official (60min)",
            "Day-ahead transmission capacity SE3-FI - planned (60min)",
            "Electricity consumption forecast - next 24 hours (60min)",
            "Electricity consumption forecast - updated hourly (60min)",
            "Electricity consumption in Finland (60min)",
            "Electricity consumption in Finland - real time data (3min)",
            "Electricity production in Finland (60min)",
            "Electricity production in Finland - real time data (3min)",
            "Electricity production prediction - updated hourly (60min)",
            "Electricity production prediction - premilinary (60min)",
            "Electricity production, reserve power plants and small-scale production - real time data (3min)",
            "Electricity production, surplus/deficit - real time data (3min)",
            "Electricity shortage status (3min)",
            "Emission factor for electricity consumed in Finland - real time data (3min)",
            "Emission factor of electricity production in Finland - real time data (3min)",
            "Fast Frequency Reserve FFR, price (60min)",
            "Fast Frequency Reserve FFR, procurement forecast (60min)",
            "Fast Frequency Reserve FFR, procured volume (60min)",
            "Fast Frequency Reserve FFR, received bids (60min)",
            "Frequency containment reserves for disturbances downwards regulation, hourly market prices (60min)",
            "Frequency containment reserves for disturbances downward regulation, nordic trade (60min)",
            "Frequency containment reserve for disturbances downwards regulation, procured volumes in hourly market (60min)",
            "Frequency containment reserve for disturbances downwards regulation, received bids in hourly market (60min)",
            "Frequency containment reserves for disturbances downward regulation, reserve plans in the yearly market (60min)",
            "Frequency containment reserves for disturbances upwards regulation, hourly market prices (60min)",
            "Frequency containment reserves for disturbances upwards regulation, nordic trade (60min)",
            "Frequency containment reserve for disturbances upwards regulation, procured volumes in hourly market (60min)",
            "Frequency containment reserve for disturbances upwards regulation, received bids in hourly market (60min)",
            "Frequency containment reserves for disturbances upwards regulation, reserve plans in the yearly market (60min)",
            "Frequency Containment Reserve for Normal operation, activated (60min)",
            "Frequency Containment Reserve for Normal operation, foreign trade (60min)",
            "Frequency Containment Reserve for Normal operation, hourly market bids (60min)",
            "Frequency Containment Reserve for Normal operation, hourly market prices (60min)",
            "Frequency Containment Reserve for Normal operation, hourly market volumes (60min)",
            "Frequency Containment Reserve for Normal operation, yearly market plans (60min)",
            "Frequency - real time data (3min)",
            "Hour change regulation, down-regulation (60min)",
            "Hour change regulation, up-regulation (60min)",
            "Hydro power production - real time data (3min)",
            "Imbalance price (60min)",
            "Imbalance power between Finland and Sweden (60min)",
            "Incentivising Component (IC) DK1 (60min)",
            "Incentivising Component (IC) DK2 (60min)",
            "Incentivising Component (IC) FI (60min)",
            "Incentivising Component (IC) NO1 (60min)",
            "Incentivising Component (IC) NO2 (60min)",
            "Incentivising Component (IC) NO3 (60min)",
            "Incentivising Component (IC) NO4 (60min)",
            "Incentivising Component (IC) NO5 (60min)",
            "Incentivising Component (IC) SE1 (60min)",
            "Incentivising Component (IC) SE2 (60min)",
            "Incentivising Component (IC) SE3 (60min)",
            "Incentivising Component (IC) SE4 (60min)",
            "Industrial cogeneration - real time data (3min)",
            "Intraday transmission capacity EE-FI (60min)",
            "Intraday transmission capacity EE-FI - real time data (60min)",
            "Intraday transmission capacity FI-EE (60min)",
            "Intraday transmission capacity FI-EE - real time data (60min)",
            "Intraday transmission capacity FI-RUS (60min)",
            "Intraday transmission capacity FI - SE1 (60min)",
            "Intraday transmission capacity FI-SE3 (60min)",
            "Intraday transmission capacity RUS-FI (60min)",
            "Intraday transmission capacity SE1-FI (60min)",
            "Intraday transmission capacity SE3-FI (60min)",
            "Kinetic energy of the Nordic power system - real time data (1min)",
            "Measured transmission of electricity in Finland from north to south (60min)",
            "Net import/export of electricity - real time data (3min)",
            "Nuclear power production - real time data (3min)",
            "Ordered down-regulations from Balancing energy market in Finland (60min)",
            "Ordered up-regulations from Balancing energy market in Finland (60min)", 
            "Other power transactions, down-regulation (60min)",
            "Other power transactions, up-regulation (60min)",
            "Peak load power - real time data (3min)",
            "Planned transmission capacity FI-RUS (60min)",
            "Planned transmission capacity RUS-FI (60min)",
            "Planned weekly capacity from north to south (60min)",
            "Planned weekly capacity from south to north (60min)",
            "Power system state - real time data (3min)",
            "Price of the last activated up-regulation bid - real time data (60min)",
            "Solar power generation forecast - updated hourly (60min)",
            "Solar power generation forecast - updated once a day (24h)",
            "Special regulation, up-regulation (60min)",
            "Special regulation, down-regulation (60min)",
            "Stock exchange capacity FI-RUS (60min)",
            "Stock exchange trade FI-RUS-FI (60min)",
            "Stock exchange capacity RUS-FI (60min)",
            "Surplus/deficit, cumulative - real time data (3min)",
            "Temperature in Helsinki - real time data",
            "Temperature in Jyväskylä - real time data (3min)",
            "Temperature in Oulu - real time data (3min)",
            "Temperature in Rovaniemi - real time data (3min)",
            "The sum of the down-regulation bids in the Balancing energy market (60min)",
            "The sum of the up-regulation bids in the balancing energy market (60min)",
            "Time deviation - real time data (3min)",
            "Total production capacity used in the solar power forecast (60min)",
            "Total production capacity used in the wind power forecast (60min)",
            "Transmission between Finland and Central Sweden - real time data (3min)",
            "Transmission between Finland and Estonia - real time data (3min)",
            "Transmission between Finland and Northern Sweden - real time data (3min)",
            "Transmission between Finland and Norway - real time data (3min)",
            "Transmission between Finland and Russia - real time data (3min)",
            "Transmission between Finland and Åland - real time data (3min)",
            "Transmission capacity FI-RUS (60min)",
            "Transmission capacity RUS-FI (60min)",
            "Transmission of electricity between Finland and Central Sweden - measured hourly data (60min)",
            "Transmission of electricity between Finland and Estonia - measured hourly data (60min)",
            "Transmission of electricity between Finland and Northern Sweden - measured hourly data (60min)",
            "Transmission of electricity between Finland and Norway - measured hourly data (60min)",
            "Transmission of electricity between Finland and Russia - measured hourly data (60min)",
            "Transmission of electricity between Finland and Åland - measured hourly data (60min)",
            "Up-regulating price in the Balancing energy market (60min)",
            "Value of Avoided Activation (VoAA) DK1 (60min)",
            "Value of Avoided Activation (VoAA) DK2 (60min)",
            "Value of Avoided Activation (VoAA) FI (60min)",
            "Value of Avoided Activation (VoAA) NO1 (60min)",
            "Value of Avoided Activation (VoAA) NO2 (60min)",
            "Value of Avoided Activation (VoAA) NO3 (60min)",
            "Value of Avoided Activation (VoAA) NO4 (60min)",
            "Value of Avoided Activation (VoAA) NO5 (60min)",
            "Value of Avoided Activation (VoAA) SE1 (60min)",
            "Value of Avoided Activation (VoAA) SE3 (60min)",
            "Value of Avoided Activation (VoAA) SE4 (60min)",
            "Wind power generation forecast - updated hourly (60min)",
            "Wind power generation forecast - updated once a day (24h)",
            "Wind power generation - hourly data (60min)",
            "Wind power production - real time data (3min)"    
        ],
        id: 
        [
            252,
            253,
            53,
            54,
            47,
            46,
            51,
            52,
            329,
            331,
            330,
            328,
            335,
            333,
            332,
            334,
            327,
            68,
            101,
            65,
            49,
            64,
            201,
            140,
            31,
            32,
            86,
            85,
            112,
            115,
            26,
            143,
            27,
            145,
            24,
            142,
            25,
            144,
            165,
            166,
            124,
            193,
            74,
            192,
            242,
            241,
            205,
            198,
            336,
            265,
            266,
            277,
            278,
            276,
            275,
            283,
            320,
            281,
            282,
            321,
            318,
            289,
            315,
            286,
            290,
            123,
            287,
            285,
            317,
            316,
            288,
            177,
            239,
            240,
            191,
            45,
            176,
            303,
            304,
            305,
            306,
            307,
            308,
            309,
            310,
            311,
            312,
            313,
            314,
            202,
            110,
            111,
            113,
            114,
            50,
            44,
            45,
            66,
            38,
            39,
            260,
            30,
            194,
            188,
            33,
            34,
            213,
            214,
            183,
            41,
            127,
            28,
            29,
            209,
            22,
            248,
            247,
            118,
            119,
            102,
            69,
            67,
            186,
            178,
            182,
            196,
            185,
            105,
            830,
            206,
            267,
            268,
            89,
            180,
            87,
            187,
            195,
            90,
            103,
            63,
            61,
            55,
            60,
            57,
            58,
            280,
            45,
            291,
            292,
            293,
            294,
            295,
            296,
            297,
            298,
            299,
            301,
            302,
            245,
            246,
            75,
            181
        ],
        unit: [
            "MW",
            "MW",
            "MWh/h",
            "MWh/h",
            "MW",
            "MW",
            "€/MW",
            "€/MW",
            "€/MW",
            "MW",
            "€/MW",
            "MW/h",
            "MW",
            "",
            "MW",
            "MW",
            "",
            "MWh/h",
            "MW",
            "MW",
            "MW",
            "MW",
            "MW",
            "MWh/h",
            "MWh/h",
            "MWh/h",
            "€/MWh",
            "€/MWh",
            "MW",
            "MW",
            "MW",
            "MW",
            "MW",
            "MW",
            "MW",
            "MW",
            "MW",
            "MW",
            "MWh/h",
            "MWh/h",
            "MWh/h",
            "MW",
            "MWh/h",
            "MW",
            "MWh/h",
            "MWh/h",
            "MW",
            "MW",
            "",
            "gCO2/kWh",
            "gCO2/kWh",
            "€/MW",
            "MW",
            "MW",
            "MW",
            "€/MW",
            "MW",
            "MW",
            "MW",
            "MW",
            "€/MW",
            "MW",
            "MW",
            "MW",
            "MW",
            "MWh/h",
            "MW",
            "MW",
            "€/MW",
            "MW",
            "MW",
            "Hz",
            "MWh/h",
            "MWh/h",
            "MW",
            "€/MWh",
            "MWh/h",
            "€/MWh",
            "€/MWh",
            "€/MWh",
            "€/MWh",
            "€/MWh",
            "€/MWh",
            "€/MWh",
            "€/MWh",
            "€/MWh",
            "€/MWh",
            "€/MWh",
            "€/MWh",
            "MW",
            "MW",
            "MW",
            "MW",
            "MW",
            "MW",
            "MW",
            "MW",
            "MW",
            "MW",
            "MW",
            "GWs",
            "MWh/h",
            "MW",
            "MW",
            "MWh/h",
            "MWh/h",
            "MWh/h",
            "MWh/h",
            "MW",
            "MW",
            "MW",
            "Mwh/h",
            "Mwh/h",
            "",
            "€/MWh",
            "MWh/h",
            "MWh/h",
            "MWh/h",
            "MWh/h",
            "MW",
            "MWh/h",
            "MW",
            "MW",
            "°C",
            "°C",
            "°C",
            "°C",
            "MW",
            "MW",
            "",
            "MW",
            "MW",
            "MWh/h",
            "MW",
            "MW",
            "MW",
            "MW",
            "MW",
            "MW",
            "MW",
            "MW",
            "MWh/h",
            "MWh/h",
            "MWh/h",
            "MWh/h",
            "MWh/h",
            "€/MWh",
            "€/MWh",
            "€/MWh",
            "€/MWh",
            "€/MWh",
            "€/MWh",
            "€/MWh",
            "€/MWh",
            "€/MWh",
            "€/MWh",
            "€/MWh",
            "€/MWh",
            "MWh/h",
            "MWh/h",
            "MWh/h",
            "MW"
        ],
        hyperlink:
        [
            "https://data.fingrid.fi/en/dataset/aktivoitu-alassaatoteho",
            "https://data.fingrid.fi/en/dataset/aktivoitu-ylossaatoteho",
            "https://data.fingrid.fi/en/dataset/activated-automatic-frequency-restoration-reserve-down",
            "https://data.fingrid.fi/en/dataset/activated-automatic-frequency-restoration-reserve-up",
            "https://data.fingrid.fi/en/dataset/procured-automatic-frequency-restoration-reserve-capacity-down",
            "https://data.fingrid.fi/en/dataset/procured-automatic-frequency-restoration-reserve-capacity-up",
            "https://data.fingrid.fi/en/dataset/procured-afrr-capacity-price-down",
            "https://data.fingrid.fi/en/dataset/procured-a-frr-capacity-price-up",
            "https://data.fingrid.fi/en/dataset/saatokapasiteetti-mfrr-ylos-tuntimarkkina-marginaalihinta",
            "https://data.fingrid.fi/en/dataset/saatokapasiteetti-mfrr-alas-tuntimarkkina-tarjoukset",
            "https://data.fingrid.fi/en/dataset/saatokapasiteetti-mfrr-alas-tuntimarkkina-marginaalihinta",
            "https://data.fingrid.fi/en/dataset/saatokapasiteetti-mfrr-alas-tuntimarkkina-toteutunut-hankinta",
            "https://data.fingrid.fi/en/dataset/saatokapasiteetti-mfrr-alas-tuntimarkkina-hankintaennuste",
            "https://data.fingrid.fi/en/dataset/saatokapasiteettimarkkinat-tuntimarkkina-toteutunut-hankinta-virosta",
            "https://data.fingrid.fi/en/dataset/saatokapasiteetti-mfrr-ylos-tuntimarkkina-tarjoukset",
            "https://data.fingrid.fi/en/dataset/saatokapasiteetti-mfrr-ylos-tuntimarkkina-hankintaennuste",
            "https://data.fingrid.fi/en/dataset/saatokapasiteetti-mfrr-ylos-tuntimarkkina-toteutunut-hankinta",
            "https://data.fingrid.fi/en/dataset/bilateral-trade-between-finland-and-russia",
            "https://data.fingrid.fi/en/dataset/bilateral-trade-capacity-fi-rus",
            "https://data.fingrid.fi/en/dataset/bilateral-trade-capacity-rus-fi",
            "https://data.fingrid.fi/en/dataset/unused-bilateral-trade-capacity-fi-rus",
            "https://data.fingrid.fi/en/dataset/unused-bilateral-trade-capacity-rus-fi",
            "https://data.fingrid.fi/en/dataset/cogeneration",
            "https://data.fingrid.fi/en/dataset/commercial-flow-fi-ee",
            "https://data.fingrid.fi/en/dataset/commercial-flow-fi-se1",
            "https://data.fingrid.fi/en/dataset/commercial-flow-fi-se3",
            "https://data.fingrid.fi/en/dataset/cross-border-transmission-fee-export-to-russia",
            "https://data.fingrid.fi/en/dataset/cross-border-transmission-fee-import-from-russia",
            "https://data.fingrid.fi/en/dataset/intra-day-transmission-capacity-ee-fi",
            "https://data.fingrid.fi/en/dataset/indra-day-transmission-capacity-fi-ee",
            "https://data.fingrid.fi/en/dataset/vuorokausimarkkinoille-annettu-siirtokapasiteetti-fi-se1",
            "https://data.fingrid.fi/en/dataset/planned-transmission-capacity-fi-se1",
            "https://data.fingrid.fi/en/dataset/vuorokausimarkkinoille-annettu-siirtokapasiteetti-fi-se3",
            "https://data.fingrid.fi/en/dataset/suunniteltu-vuorokausimarkkinoille-annettava-siirtokapasiteetti-fi-se3",
            "https://data.fingrid.fi/en/dataset/intra-day-transmission-capacity-se1-fi",
            "https://data.fingrid.fi/en/dataset/planned-transmission-capacity-se1-fi",
            "https://data.fingrid.fi/en/dataset/vuorokausimarkkinoille-annettu-siirtokapasiteetti-se3-fi",
            "https://data.fingrid.fi/en/dataset/planned-day-ahead-transmission-capacity-se3-fi",
            "https://data.fingrid.fi/en/dataset/an-hourly-comsumption-forecast-for-the-next-24-hours",
            "https://data.fingrid.fi/en/dataset/updated-electricity-consumption-forecast-of-finland",
            "https://data.fingrid.fi/en/dataset/electricity-consumption-in-finland",
            "https://data.fingrid.fi/en/dataset/electricity-consumption-in-finland-real-time-data",
            "https://data.fingrid.fi/en/dataset/electricity-production-in-finland",
            "https://data.fingrid.fi/en/dataset/electricity-production-in-finland-real-time-data",
            "https://data.fingrid.fi/en/dataset/tentative-production-prediction-for-the-next-24-hours-as-an-hourly-energy",
            "https://data.fingrid.fi/en/dataset/finland-electricity-production-prediction-based-on-production-plans-informed-to-fingrid",
            "https://data.fingrid.fi/en/dataset/gas-turbine-and-estimated-small-scale-production-real-time-data",
            "https://data.fingrid.fi/en/dataset/production-surplus-deficit-in-finland-real-time-data",
            "https://data.fingrid.fi/en/dataset/sahkopulan-tilannetieto-reaaliaikatieto",
            "https://data.fingrid.fi/en/dataset/suomessa-kulutetun-sahkon-paastokerroin-reaaliaikatieto",
            "https://data.fingrid.fi/en/dataset/suomen-sahkontuotannon-paastokerroin-reaaliaikatieto",
            "https://data.fingrid.fi/en/dataset/nopea-taajuusreservi-hinta",
            "https://data.fingrid.fi/en/dataset/nopea-taajuusreservi-hankintaennuste",
            "https://data.fingrid.fi/en/dataset/nopea-taajuusreservi-hankintamaara",
            "https://data.fingrid.fi/en/dataset/nopea-taajuusreservi-tarjoukset",
            "https://data.fingrid.fi/en/dataset/taajuusohjattu-hairioreservi-alassaato-tuntimarkkinahinnat",
            "https://data.fingrid.fi/en/dataset/taajuusohjattu-hairioreservi-alassaato-ulkomaankauppa",
            "https://data.fingrid.fi/en/dataset/taajuusohjattu-hairioreservi-alassaato-hankintamaarat-tuntimarkkinoilta",
            "https://data.fingrid.fi/en/dataset/taajuusohjattu-hairioreservi-alassaato-tarjousmaarat-tuntimarkkinoilta",
            "https://data.fingrid.fi/en/dataset/taajuusohjattu-hairioreservi-alassaato-vuosimarkkinasuunnitelmat",
            "https://data.fingrid.fi/en/dataset/frequency-containment-reserves-for-disturbances-hourly-market-prices",
            "https://data.fingrid.fi/en/dataset/taajuusohjattu-hairioreservi-ulkomaankauppa",
            "https://data.fingrid.fi/en/dataset/frequency-containment-reserve-for-disturbances-procured-volumes-in-hourly-market",
            "https://data.fingrid.fi/en/dataset/taajuusohjattu-hairioreservi-tarjousmaarat-tuntimarkkinoilta",
            "https://data.fingrid.fi/en/dataset/taajuusohjattu-hairioreservi-vuosimarkkinasuunnitelmat",
            "https://data.fingrid.fi/en/dataset/activated-frequency-containment-reserve-for-normal-operation",
            "https://data.fingrid.fi/en/dataset/taajuusohjattu-kayttoreservi-ulkomaankauppa",
            "https://data.fingrid.fi/en/dataset/taajuusohjattu-kayttoreservi-tarjousmaarat-tuntimarkkinoilta",
            "https://data.fingrid.fi/en/dataset/frequency-containment-reserve-for-normal-operation-prices",
            "https://data.fingrid.fi/en/dataset/frequency-containment-reserves-for-normal-operation-procured-volumes-in-hourly-market",
            "https://data.fingrid.fi/en/dataset/taajuusohjattu-kayttoreservi-vuosimarkkinasuunnitelmat",
            "https://data.fingrid.fi/en/dataset/frequency-real-time-data",
            "https://data.fingrid.fi/en/dataset/tunninvaihdesaato-alassaato",
            "https://data.fingrid.fi/en/dataset/hour-change-regulation-up-regulation",
            "https://data.fingrid.fi/en/dataset/hydro-power-production-real-time-data",
            "https://data.fingrid.fi/en/dataset/fi_ts_myyntihinta",
            "https://data.fingrid.fi/en/dataset/imbalance-power-between-finland-and-sweden",
            "https://data.fingrid.fi/en/dataset/ic_dk1",
            "https://data.fingrid.fi/en/dataset/ic_dk2",
            "https://data.fingrid.fi/en/dataset/ic_fi",
            "https://data.fingrid.fi/en/dataset/ic_no1",
            "https://data.fingrid.fi/en/dataset/ic_no2",
            "https://data.fingrid.fi/en/dataset/ic_no3",
            "https://data.fingrid.fi/en/dataset/ic_no4",
            "https://data.fingrid.fi/en/dataset/ic_no5",
            "https://data.fingrid.fi/en/dataset/ic_se1",
            "https://data.fingrid.fi/en/dataset/ic_se2",
            "https://data.fingrid.fi/en/dataset/ic_se3",
            "https://data.fingrid.fi/en/dataset/ic_se4",
            "https://data.fingrid.fi/en/dataset/industrial-cogeneration-real-time-data",
            "https://data.fingrid.fi/en/dataset/transmission-capacity-to-be-given-to-intraday-market-ee-fi",
            "https://data.fingrid.fi/en/dataset/real-time-transmission-capacity-to-be-given-to-intraday-market-ee-fi",
            "https://data.fingrid.fi/en/dataset/intraday-markkinoille-annettu-siirtokapasiteetti-ee-fi",
            "https://data.fingrid.fi/en/dataset/real-time-transmission-capacity-to-be-given-to-intraday-market-fi-ee",
            "https://data.fingrid.fi/en/dataset/intraday-transmission-capacity-fi-rus",
            "https://data.fingrid.fi/en/dataset/transmission-capacity-to-be-given-to-intraday-market-fi-se1",
            "https://data.fingrid.fi/en/dataset/transmission-capacity-to-be-given-to-intraday-market-fi-se3",
            "https://data.fingrid.fi/en/dataset/intraday-transmission-capacity-rus-fi",
            "https://data.fingrid.fi/en/dataset/transmission-capacity-to-be-given-to-intraday-market-se1-fi",
            "https://data.fingrid.fi/en/dataset/transmission-capacity-to-be-given-to-intraday-market-se3-fi",
            "https://data.fingrid.fi/en/dataset/kinetic-energy-nordic-realtime",
            "https://data.fingrid.fi/en/dataset/measured-electricity-energy-in-finland-from-north-to-south",
            "https://data.fingrid.fi/en/dataset/net-import-export-of-electricity-real-time-data",
            "https://data.fingrid.fi/en/dataset/nuclear-power-production-real-time-data",
            "https://data.fingrid.fi/en/dataset/ordered-down-regulations-from-balancing-market-in-finland",
            "https://data.fingrid.fi/en/dataset/ordered-up-regulations-from-balancing-energy-market-in-finland",
            "https://data.fingrid.fi/en/dataset/other-power-transactions-down-regulation",
            "https://data.fingrid.fi/en/dataset/other-power-transactions-up-regulation",
            "https://data.fingrid.fi/en/dataset/peak-load-power-real-time-data",
            "https://data.fingrid.fi/en/dataset/planned-transmission-capacity-fi-rus",
            "https://data.fingrid.fi/en/dataset/planned-transmission-capacity-rus-fi",
            "https://data.fingrid.fi/en/dataset/planned-weekly-capacity-from-north-to-south-defined-by-fingrid",
            "https://data.fingrid.fi/en/dataset/planned-weekly-capacity-from-south-to-north-defined-by-fingrid",
            "https://data.fingrid.fi/en/dataset/power-system-state-real-time-data",
            "https://data.fingrid.fi/en/dataset/real-time-price-of-up-regulation",
            "https://data.fingrid.fi/en/dataset/solar-power-generation-forecast-updated-every-hour",
            "https://data.fingrid.fi/en/dataset/solar-power-generation-forecast-updated-once-a-day",
            "https://data.fingrid.fi/en/dataset/erikoissaato-alassaato",
            "https://data.fingrid.fi/en/dataset/special-regulation-up-regulation",
            "https://data.fingrid.fi/en/dataset/stock-exchange-capacity-fi-rus",
            "https://data.fingrid.fi/en/dataset/stock-exchange-between-finland-and-russia",
            "https://data.fingrid.fi/en/dataset/stock-exchange-capacity-rus-fi",
            "https://data.fingrid.fi/en/dataset/surplus-deficit-cumulative-real-time-data",
            "https://data.fingrid.fi/en/dataset/temperature-in-helsinki-real-time-data",
            "https://data.fingrid.fi/en/dataset/temperature-in-jyvaskyla-real-time-data",
            "https://data.fingrid.fi/en/dataset/temperature-in-oulu-real-time-data",
            "https://data.fingrid.fi/en/dataset/temperature-in-rovaniemi-real-time-data",
            "https://data.fingrid.fi/en/dataset/the-sum-of-the-down-regualtion-bids-in-the-balancing-energy-market",
            "https://data.fingrid.fi/en/dataset/the-sum-of-the-up-regulation-bids-in-the-balancing-energy-market",
            "https://data.fingrid.fi/en/dataset/time-deviation-real-time-data",
            "https://data.fingrid.fi/en/dataset/total-solar-production-capacity",
            "https://data.fingrid.fi/en/dataset/total-wind-production-capacity",
            "https://data.fingrid.fi/en/dataset/transmission-between-finland-and-central-sweden-real-time-data",
            "https://data.fingrid.fi/en/dataset/transmission-between-finland-and-estonia-real-time-data",
            "https://data.fingrid.fi/en/dataset/transmission-between-finland-and-northern-sweden-real-time-data",
            "https://data.fingrid.fi/en/dataset/transmission-between-finland-and-norway-real-time-data",
            "https://data.fingrid.fi/en/dataset/transmission-between-finland-and-russia-real-time-data",
            "https://data.fingrid.fi/en/dataset/transmission-between-sweden-and-aland-real-time-data",
            "https://data.fingrid.fi/en/dataset/summakapasiteetti-fi-rus",
            "https://data.fingrid.fi/en/dataset/transmission-capacity-rus-fi",
            "https://data.fingrid.fi/en/dataset/measured-electrical-transmission-between-finland-and-central-sweden",
            "https://data.fingrid.fi/en/dataset/measured-electrical-transmission-between-finland-and-estonia",
            "https://data.fingrid.fi/en/dataset/measured-transmission-of-electiricity-between-finland-and-northern-sweden",
            "https://data.fingrid.fi/en/dataset/measured-electrical-transmission-between-finland-and-norway",
            "https://data.fingrid.fi/en/dataset/measured-transmission-of-electricity-between-finland-and-russia",
            "https://data.fingrid.fi/en/dataset/measured-electrical-transmission-between-finland-and-aland",
            "https://data.fingrid.fi/en/dataset/up-regulating-price-in-the-balancing-energy-market",
            "https://data.fingrid.fi/en/dataset/voaa_dk1",
            "https://data.fingrid.fi/en/dataset/voaa_dk2",
            "https://data.fingrid.fi/en/dataset/voaa_fi",
            "https://data.fingrid.fi/en/dataset/voaa_no1",
            "https://data.fingrid.fi/en/dataset/voaa_no2",
            "https://data.fingrid.fi/en/dataset/voaa_no3",
            "https://data.fingrid.fi/en/dataset/voaa_no4",
            "https://data.fingrid.fi/en/dataset/voaa_no5",
            "https://data.fingrid.fi/en/dataset/voaa_se1",
            "https://data.fingrid.fi/en/dataset/voaa_se3",
            "https://data.fingrid.fi/en/dataset/voaa_se4",
            "https://data.fingrid.fi/en/dataset/wind-power-generation-forecast-updated-every-hour",
            "https://data.fingrid.fi/en/dataset/wind-power-generation-forecast-updated-once-a-day",
            "https://data.fingrid.fi/en/dataset/wind-power-generation",
            "https://data.fingrid.fi/en/dataset/wind-power-production-real-time-data"
        ],
        description: 
        [
            "The activated downward power from balancing power market. The value is given for each 15 minutes and indicated the amount of activated power in the end of each 15 minute time period. The values are available starting from December 2018.",
            "The activated upward power from balancing power market. The value is given for each 15 minutes and indicated the amount of activated power in the end of each 15 minute time period. The values are available starting from December 2018.",
            "Activated automatic Frequency Restoration Reserve (aFRR) energy, down [MWh]",
            "Activated automatic Frequency Restoration Reserve (aFRR) energy, up [MWh]",
            "Procured automatic Frequency Restoration Reserve (aFRR) capacity, down [MW]",
            "Procured automatic Frequency Restoration Reserve (aFRR) capacity, up [MW]",
            "Marginal price for procured automatic Frequency Restoration Reserve (aFRR) capacity for down-regulation [€/MW]",
            "Marginal price for procured upward automatic Frequency Restoration Reserve (aFRR) capacity [€/MW]",
            "Data before 30.11.2022 is test-data. The marginal price of upwards balancing capacity procured from the balancing capacity market, €/MW,h. Fingrid procures mFRR capacity through the balancing capacity market auction, which is held when needed. Balance service provider pledges itself to leave regulating bids on the regulation market. For that the balance service provider is entitled to capacity payment.",
            "Data before 30.11.2022 is test-data. The amount of downwards balancing capacity bids in the balancing capacity market, MW/h. Fingrid procures mFRR capacity through the balancing capacity market, which is held when needed. Balance service provider pledges itself to leave regulating bids on the regulation market. For that the balance service provider is entitled to capacity payment.",
            "Data before 30.11.2022 is test-data. The marginal price of downwards balancing capacity procured from the balancing capacity market, €/MW,h. Fingrid procures mFRR capacity through the balancing capacity market auction, which is held when needed. Balance service provider pledges itself to leave regulating bids on the regulation market. For that the balance service provider is entitled to capacity payment.",
            "Data before 30.11.2022 is test-data. The amount of downwards balancing capacity procured from the balancing capacity market, MW/h. Fingrid procures mFRR capacity through the balancing capacity market auction, which is held when needed. Balance service provider pledges itself to leave regulating bids on the regulation market. For that the balance service provider is entitled to capacity payment.",
            "Data before 30.11.2022 is test-data. The forecasted amount of downwards balancing capacity procurement [MW/h]. Fingrid procures mFRR capacity through the balancing capacity market, which is held when needed. Balance service provider pledges itself to leave regulating bids on the regulation market. For that the balance service provider is entitled to capacity payment.",
            "Data before 30.11.2022 is test-data.  In addition to the national weekly market, Fingrid also has the possibility to procure mFRR balancing capacity from Estonia. This dataset includes the procured balancing capacity amounts from Estonia, MW/week. The procured amount is published at latest on Friday of the week before the procurement week at 12:00 (EET).",
            "Data before 30.11.2022 is test-data. The amount of upwards balancing capacity bids in the balancing capacity market, MW/h. Fingrid procures mFRR capacity through the balancing capacity market, which is held when needed. Balance service provider pledges itself to leave regulating bids on the regulation market. For that the balance service provider is entitled to capacity payment.",
            "Data before 30.11.2022 is test-data. The forecasted amount of upwards balancing capacity procurement [MW/h].  Fingrid procures mFRR capacity through the balancing capacity market, which is held when needed. Balance service provider pledges itself to leave regulating bids on the regulation market. For that the balance service provider is entitled to capacity payment.",
            "Data before 30.11.2022 is test-data. The amount of upwards balancing capacity procured from the balancing capacity market, MW/h. Fingrid procures mFRR capacity through the balancing capacity market auction, which is held when needed. Balance service provider pledges itself to leave regulating bids on the regulation market. For that the balance service provider is entitled to capacity payment.",
            "Bilateral trade between Finland and Russia. Fingrid and the Russian parties confirm the bilateral trades on 400 kV cross-border connection in the morning of the commercial day D for the following commercial day D+1. The confirmed bilateral trades will be bid price-independently on the electricity spot market",
            "The bilateral capacity on the 400 kV connection from Russia to Finland that is reserved to bilateral trade of the following commercial day. The capacity is confirmed by Fingrid and the Russian parties.",
            "The bilateral capacity on the 400 kV connection from Russia (RUS) to Finland (FI) that is reserved to bilateral trade of the following commercial day. The capacity is confirmed by Fingrid and the Russian parties.",
            "Unused bilateral trade capacity from Finland (FI) to Russia (RUS). The capacity of electricity transmission in bilateral trade can be left unused if the parties do not export the maximum amount of electricity to Russia.",
            "Unused bilateral trade capacity From Russia (RUS) to Finland (FI). The capacity of electricity transmission in bilateral trade can be left unused if the parties do not import the maximum amount of electricity to Finland.",
            "Cogeneration of district heating based on the real-time measurements in Fingrid's operation control system. The data is updated every 3 minutes. Cogeneration means power plants that produce both electricity and district heating or process steam (combined heat and power, CHP).",
            "Commercial electricity flow (dayahead market and intraday market) between Finland (FI) and Estonia (EE) including system supportive trade between TSOs. Positive sign is export from Finland to Estonia.",
            "Commercial transmission of electricity (dayahead market and intraday market) between Finland (FI) and Northern Sweden (SE1). Positive sign is export from Finland to Sweden.",
            "Commercial electricity flow (dayahead market and intraday market) between Finland (FI) and Central Sweden (SE3). Positive sign is export from Finland to Sweden.",
            "Hourly cross-border transmission fee (dynamic tariff) for exports to Russia on Fingrid's connections.",
            "Hourly cross-border transmission fee (dynamic tariff) for imports from Russia on Fingrid's connections.",
            "Day-ahead transmission capacity from Estonia (EE) to Finland (FI). Transmission capacity is given hourly for every hour of the next day. Each hour is given one value. Day-ahead transmission capacity Fingrid will publish every day in the afternoon. This capacity will not changed after publication. Transmission capacity mean the capability of the electricity system to supply electricity to the market without compromising the system security.",
            "Day-ahead transmission capacity from Finland (FI) to Estonia (EE). Transmission capacity is given hourly for every hour of the next day. Each hour is given one value. Day-ahead transmission capacity Fingrid will publish every day in the afternoon. This capacity will not changed after publication. Transmission capacity mean the capability of the electricity system to supply electricity to the market without compromising the system security.",
            "Day-ahead transmission capacity from Finland (FI) to North-Sweden (SE1). Transmission capacity is given hourly for every hour of the next day. Each hour is given one value. Day-ahead transmission capacity Fingrid will publish every day in the afternoon. This capacity will not changed after publication. Transmission capacity mean the capability of the electricity system to supply electricity to the market without compromising the system security.",
            "Planned day-ahead transmission capacity from Finland (FI) to North-Sweden (SE1). Transmission capacity is given hourly for every next week hour. Each week's hour is given one value. Planned weekly transmission capacity Fingrid will publish every Tuesday. Information will be updated if there are changes to the previous plan timetable or capacity. Transmission capacity mean the capability of the electricity system to supply electricity to the market without compromising the system security.",
            "Day-ahead transmission capacity from Finland (FI) to Central-Sweden (SE3). Transmission capacity is given hourly for every hour of the next day. Each hour is given one value. Day-ahead transmission capacity Fingrid will publish every day in the afternoon. This capacity will not changed after publication. Transmission capacity mean the capability of the electricity system to supply electricity to the market without compromising the system security.",
            "Planned day-ahead transmission capacity from Finland (FI) to Central-Sweden (SE3). Transmission capacity is given hourly for every next week hour. Each week's hour is given one value. Planned weekly transmission capacity Fingrid will publish every Tuesday. Information will be updated if there are changes to the previous plan timetable or capacity. Transmission capacity mean the capability of the electricity system to supply electricity to the market without compromising the system security.",
            "Day-ahead transmission capacity from North-Sweden (SE1) to Finland (FI). Transmission capacity is given hourly for every hour of the next day. Each hour is given one value. Day-ahead transmission capacity Fingrid will publish every day in the afternoon. This capacity will not changed after publication. Transmission capacity mean the capability of the electricity system to supply electricity to the market without compromising the system security.",
            "Planned day-ahead transmission capacity from North-Sweden (SE1) to Finland (FI). Transmission capacity is given hourly for every next week hour. Each week's hour is given one value. Planned weekly transmission capacity Fingrid will publish every Tuesday. Information will be updated if there are changes to the previous plan timetable or capacity. Transmission capacity mean the capability of the electricity system to supply electricity to the market without compromising the system security.",
            "Day-ahead transmission capacity from Central-Sweden (SE3) to Finland (FI). Transmission capacity is given hourly for every hour of the next day. Each hour is given one value. Day-ahead transmission capacity Fingrid will publish every day in the afternoon. This capacity will not changed after publication. Transmission capacity mean the capability of the electricity system to supply electricity to the market without compromising the system security.",
            "Planned day-ahead transmission capacity from Central-Sweden (SE3) to Finland (FI). Transmission capacity is given hourly for every next week hour. Each week's hour is given one value. Planned weekly transmission capacity Fingrid will publish every Tuesday. Information will be updated if there are changes to the previous plan timetable or capacity. Transmission capacity mean the capability of the electricity system to supply electricity to the market without compromising the system security.",
            "An hourly consumption forecast for the next 24 hours made by Fingrid. Forecast is published on previous day at 12:00 EET.",
            "Electricity consumption forecast of Finland. The forecast is made by Fingrid and updated hourly.",
            "Electricity consumption in Finland is based on Fingrid's production measurements. Minor part of production which is not measured is estimated.  The consumption is calculated as follows: Consumption = Production + Import - Export. Updated hourly.",
            "Electricity consumption in Finland is calculated based on production and import/export. The data is updated every 3 minutes.  Production information and import/export are based on the real-time measurements in Fingrid's operation control system.",
            "Hourly electricity production in Finland are based on Fingrid's measurements. Minor part of production which is not measured is estimated.  Updated hourly.",
            "Electricity production in Finland based on the real-time measurements in Fingrid's operation control system The data is updated every 3 minutes.",
            "Hourly electricity generation forecast is based on the production plans that balance responsible parties have reported to Fingrid. The forecast is published daily by 6.00 pm for the next day, and it is not updated to match the updated production plans that balance responsible parties send to Fingrid hourly.",
            "The calculation of production forecast in Finland is based on the production plans that balance responsible parties has reported to Fingrid. Production forecast is updated hourly.",
            "Reserve power plants electrical production is based on the real-time measurements in Fingrid's operation control system. Estimated small-scale production is added, of which there are no measurements available. The data is updated every 3 minutes.",
            "Finland's energy production surplus/deficit. Information is based on the real time measurements in Fingrid's power control system. Power deficit/surplus represents the balance between power production and consumption in Finland, taking into account imports and exports. Power deficit/surplus is calculated as the difference between the measured net import/export and the confirmed net exchange program between Finland and the other Nordic countries. Sign convention: production deficit -, surplus + The data is updated every 3 minutes.",
            "Electricity shortage status. An electricity shortage occurs when electricity production and imports are not enough to cover electricity consumption. In such cases, it is necessary to restrict consumption to stop the power system from crashing altogether.  Fingrid informs citizens on its website and with a press release in accordance with the three-step procedure when the situation possibly escalates. 0 = Normal 1 = Electricity shortage possible 2 = High risk of electricity shortage 3 = Electricity shortage  The data is updated every 3 minutes.",
            "Estimate of carbon dioxide of produced electricity, which is consumed in Finland. The emissions are estimated by taking FInland's electricity production, electricity import as well as electricity export into account.  The data is updated every 3 minutes.",
            "Near in real time calculated carbon dioxide emission estimate of electricity production in Finland. The emissions are estimated by summing each product of different electricity production type and their emission factor together, and by dividing the sum by Finland's total electricity production.  The data is updated every 3 minutes.",
            "The price of procured Fast Frequency Reserve (FFR) (€/MW). The price will be published 22:00 (EET) on previous evening. The price is determined by the price of the most expensive procured bid (marginal pricing). The Fast Frequency Reserve (FFR) is procured to handle low-inertia situations. The needed volume of Fast Frequency Reserve depends on the amount of inertia in the power system and the size of the reference incident.",
            "The procurement prognosis for Fast Frequency Reserve (FFR) (MW). Fingrid procures FFR based on the procurement prognosis. The prognosis is updated once a day, typically at 11:00 (EET). The Fast Frequency Reserve (FFR) is procured to handle low-inertia situations. The needed volume of Fast Frequency Reserve depends on the amount of inertia in the power system and the size of the reference incident.",
            "The volume of procured Fast Frequency Reserve (FFR). The procured volume will be published 22:00 (EET) on previous evening. The Fast Frequency Reserve (FFR) is procured to handle low-inertia situations. The needed volume of Fast Frequency Reserve depends on the amount of inertia in the power system and the size of the reference incident.",
            "The volume of received Fast Frequency Reserve (FFR) bids. The volume of bids will be published 22:00 (EET) on previous evening. The Fast Frequency Reserve (FFR) is procured to handle low-inertia situations. The needed volume of Fast Frequency Reserve depends on the amount of inertia in the power system and the size of the reference incident.",
            "Hourly prices (€/MW,h) of procured frequency containment reserve for disturbances downwards regulation (FCR-D down) in Finnish hourly market for each CET-timezone day is published previous evening at 22:45 (EET). FCR-D down is the frequency containment reserve used in the Nordic synchronous system that aims to keep the frequency below 50,5 Hz during disturbances. Hourly market is a reserve market operated by Fingrid. Procured volumes vary for each hour and price is the price of the most expensive procured bid.",
            "The volume of the nordic trade of frequency containment reserve for disturbances downward regulation (FCR-D down) capacity. Positive numbers indicate import of capacity to Finland and negative numbers indicate export of capacity from Finland. The data contains the traded capacity for Sweden and Norway. The data will be published 22:45 (EET) on previous evening. FCR-D down is the frequency containment reserve used in the Nordic synchronous system that aims to keep the frequency below 50,5 Hz during disturbances. Hourly market is a reserve market operated by Fingrid. Procured volumes vary for each hour and price is the price of the most expensive procured bid.",
            "Hourly volume of procured frequency containment reserve for disturbances downwards regulation (FCR-D down) in Finnish hourly market for each CET-timezone day is published previous evening at 22:45 (EET). FCR-D downwards regulation is the frequency containment reserve used in the Nordic synchronous system that aims to keep the frequency below 50,5 Hz during disturbances. Hourly market is a reserve market operated by Fingrid. Procured volumes vary for each hour and price is the price of the most expensive procured bid.",
            "The volume of received frequency containment reserve for disturbances downwards regulation (FCR-D down) bids. The volume of bids will be published 22:00 (EET) on previous evening. FCR-D downwards regulation is the frequency containment reserve used in the Nordic synchronous system that aims to keep the frequency below 50,5 Hz during disturbances.",
            "The hourly sum of reserve plans for frequency containment reserve for disturbances downwards regulation (FCR-D down) in the yearly market. The data will be published 22:45 (EET) on previous evening. FCR-D downwards regulation is the frequency containment reserve used in the Nordic synchronous system that aims to keep the frequency below 50,5 Hz during disturbances. Yearly market is a reserve market operated by Fingrid. Hourly procured volumes vary according to the reserve plans submitted by the balancing service providers and the price is constant over the whole year.",
            "Hourly prices (€/MW,h) of procured frequency containment reserve for disturbances upwards regulation (FCR-D up) in Finnish hourly market for each CET-timezone day is published previous evening at 22:45 (EET). FCR-D (up) is the frequency containment reserve used in the Nordic synchronous system that aims to keep the frequency above 49,5 Hz during disturbances. Hourly market is a reserve market operated by Fingrid. Procured volumes vary for each hour and price is the price of the most expensive procured bid.",
            "The volume of the nordic trade of frequency containment reserve for disturbances upwards regulation (FCR-D up) capacity. Positive numbers indicate import of capacity to Finland and negative numbers indicate export of capacity from Finland. The data contains the traded capacity for Sweden and Norway. The data will be published 22:45 (EET) on previous evening. FCR-D (up) is the frequency containment reserve used in the Nordic synchronous system that aims to keep the frequency above 49,5 Hz during disturbances. Hourly market is a reserve market operated by Fingrid. Procured volumes vary for each hour and price is the price of the most expensive procured bid.",
            "Hourly volume of procured frequency containment reserve for disturbances upwards regulation (FCR-D up) in Finnish hourly market for each CET-timezone day is published previous evening at 22:45 (EET). FCR-D (up) is the frequency containment reserve used in the Nordic synchronous system that aims to keep the frequency above 49,5 Hz during disturbances. Hourly market is a reserve market operated by Fingrid. Procured volumes vary for each hour and price is the price of the most expensive procured bid.",
            "The volume of received frequency containment reserve for disturbances upwards regulation (FCR-D up) bids. The volume of bids will be published 22:45 (EET) on previous evening. FCR-D (up) is the frequency containment reserve used in the Nordic synchronous system that aims to keep the frequency above 49,5 Hz during disturbances. Hourly market is a reserve market operated by Fingrid. Procured volumes vary for each hour and price is the price of the most expensive procured bid.",
            "The hourly sum of reserve plans for frequency containment reserve for disturbances upwards regulation (FCR-D up) in the yearly market. The data will be published 22:45 (EET) on previous evening. FCR-D (up) is the frequency containment reserve used in the Nordic synchronous system that aims to keep the frequency above 49,5 Hz during disturbances. Yearly market is a reserve market operated by Fingrid. Hourly procured volumes vary according to the reserve plans submitted by the balancing service providers and the price is constant over the whole year.",
            "Activated Frequency Containment Reserve for Normal operation (FCR-N) is published hourly one hour after the hour in question, for example the value for hour 07-08 is published at 9 o'clock.  FCR-N is the frequency containment reserve used in the Nordic synchronous system that aims to keep the frequency in normal frequency range between 49,9 - 50,1 Hz.  Activated FCR-N volume (MWh) is calculated on the basis of the frequency in the Nordic synchronous system.  Value is activated net energy. Positive value means that the frequency has been in average below 50,0 Hz during the hour, and reserve has been activated as up-regulation. Respectively, negative value means that the frequency has been in average above 50,0 Hz, and reserve has been activated as down-regulation.",
            "The volume of the foreign trade of frequency containment reserve for normal operation (FCR-N) capacity. Positive numbers indicate import of capacity to Finland and negative numbers indicate export of capacity from Finland. The data contains the traded capacity for Sweden, Norway, Estonia and Russia*. The data will be published 22:45 (EET) on previous evening. FCR-N is the frequency containment reserve used in the Nordic synchronous system that aims to keep the frequency in normal frequency range between 49,9 - 50,1 Hz. Hourly market is a reserve market operated by Fingrid. Procured volumes vary for each hour and price is the price of the most expensive procured bid. *Procuring reserves from Russia has ended 14.5.2022",
            "The volume of received Frequency Containment Reserves for Normal operation (FCR-N) bids. The volume of bids will be published 22:45 (EET) on previous evening. FCR-N is the frequency containment reserve used in the Nordic synchronous system that aims to keep the frequency in normal frequency range between 49,9 - 50,1 Hz. Hourly market is a reserve market operated by Fingrid. Procured volumes vary for each hour and price is the price of the most expensive procured bid.",
            "Hourly prices (€/MW,h) of procured frequency containment reserve for normal operation (FCR-N) in Finnish hourly market for each CET-timezone day is published previous evening at 22:45  (EET).  FCR-N is the frequency containment reserve used in the Nordic synchronous system that aims to keep the frequency in normal frequency range between 49,9 - 50,1 Hz.  Hourly market is a reserve market operated by Fingrid. Procured volumes vary for each hour and price is the price of the most expensive procured bid.",
            "Hourly volume of procured frequency containment reserve for normal operation (FCR-N) in Finnish hourly market for each CET-timezone day is published previous evening at 22:45 (EET). FCR-N is the frequency containment reserve used in the Nordic synchronous system that aims to keep the frequency in normal frequency range between 49,9 - 50,1 Hz.  Hourly market is a reserve market operated by Fingrid. Procured volumes vary for each hour and price is the price of the most expensive procured bid.",
            "The hourly sum of reserve plans for frequency containment reserve for normal operation (FCR-N) in the yearly market. The data will be published 22:45 (EET) on previous evening. FCR-N is the frequency containment reserve used in the Nordic synchronous system that aims to keep the frequency in normal frequency range between 49,9 - 50,1 Hz. Yearly market is a reserve market operated by Fingrid. Hourly procured volumes vary according to the reserve plans submitted by the balancing service providers and the price is constant over the whole year.",
            "Frequency of the power system based on the real-time measurements in Fingrid's operation control system. The data is updated every 3 minutes.",
            "In order to reduce problems encountered at the turn of the hour in the Nordic countries or in Finland, the planned production changes will be transfered to begin 15 minutes before or after the planned moment.",
            "In order to reduce problems encountered at the turn of the hour in the Nordic countries or in Finland, the planned production changes will be transfered to begin 15 minutes before or after the planned moment.",
            "Hydro power production in Finland based on the real-time measurements in Fingrid's operation control system. The data is updated every 3 minutes.",
            "Imbalance price for balance responsible party's imbalance in Single price-single position settlement from 1.11.2021 01.00 -> Prices are updated hourly.",
            "The volume of power equals to the difference between measured and commercial transmission between Finland and Sweden. The tradetypes of commercial flow include day ahead, intraday and trades between Fingrid and Svenska Kraftnät during the operational hour. When the value of imbalance power volume is positive Fingrid has sold imbalance power to Sweden.  When the value of imbalance power volume is negative Fingrid has bought imbalance power from Sweden.",
            "Incentivising Component (IC) DK1 More information about VoAA and IC can be found in eSett Handbook (definitions and calculation rules).  In case VoAA and IC cannot be calculated according to the set rules, the value 99 999 will be displayed for both.",
            "Incentivising Component (IC) DK2 More information about VoAA and IC can be found in eSett Handbook (definitions and calculation rules).  In case VoAA and IC cannot be calculated according to the set rules, the value 99 999 will be displayed for both.",
            "Incentivising Component (IC) FI More information about VoAA and IC can be found in eSett Handbook (definitions and calculation rules). In case VoAA and IC cannot be calculated according to the set rules, the value 99 999 will be displayed for both.",
            "Incentivising Component (IC) NO1 More information about VoAA and IC can be found in eSett Handbook (definitions and calculation rules). VoAA and IC are not implemented in Norway as in the other Nordic countries, but corresponding values are published for informational purposes.In case VoAA and IC cannot be calculated according to the set rules, the value 99 999 will be displayed for both.",
            "Incentivising Component (IC) NO2 More information about VoAA and IC can be found in eSett Handbook (definitions and calculation rules). VoAA and IC are not implemented in Norway as in the other Nordic countries, but corresponding values are published for informational purposes. In case VoAA and IC cannot be calculated according to the set rules, the value 99 999 will be displayed for both.",
            "Incentivising Component (IC) NO3 More information about VoAA and IC can be found in eSett Handbook (definitions and calculation rules). VoAA and IC are not implemented in Norway as in the other Nordic countries, but corresponding values are published for informational purposes. In case VoAA and IC cannot be calculated according to the set rules, the value 99 999 will be displayed for both.",
            "Incentivising Component (IC) NO4 More information about VoAA and IC can be found in eSett Handbook (definitions and calculation rules). VoAA and IC are not implemented in Norway as in the other Nordic countries, but corresponding values are published for informational purposes. In case VoAA and IC cannot be calculated according to the set rules, the value 99 999 will be displayed for both.",
            "Incentivising Component (IC) NO5 More information about VoAA and IC can be found in eSett Handbook (definitions and calculation rules). VoAA and IC are not implemented in Norway as in the other Nordic countries, but corresponding values are published for informational purposes. In case VoAA and IC cannot be calculated according to the set rules, the value 99 999 will be displayed for both.",
            "Incentivising Component (IC) SE1 More information about VoAA and IC can be found in eSett Handbook (definitions and calculation rules).  In case VoAA and IC cannot be calculated according to the set rules, the value 99 999 will be displayed for both.",
            "Incentivising Component (IC)SE2 More information about VoAA and IC can be found in eSett Handbook (definitions and calculation rules).  In case VoAA and IC cannot be calculated according to the set rules, the value 99 999 will be displayed for both.",
            "Incentivising Component (IC) SE3 More information about VoAA and IC can be found in eSett Handbook (definitions and calculation rules).  In case VoAA and IC cannot be calculated according to the set rules, the value 99 999 will be displayed for both.",
            "Incentivising Component (IC) SE4 More information about VoAA and IC can be found in eSett Handbook (definitions and calculation rules).  In case VoAA and IC cannot be calculated according to the set rules, the value 99 999 will be displayed for both.",
            "Cogeneration of industry based on the real-time measurements in Fingrid's operation control system. The data is updated every 3 minutes. Cogeneration means power plants that produce both electricity and district heating or process steam (combined heat and power, CHP).",
            "Transmission capacity to be given to intraday market EE - FI",
            "Transmission capacity to be given to intraday market EE-FI. After Elspot trades have been closed, real time intraday capacity is equivalent to the allocated intraday capacity. The real time capacity is updated after each intraday trade so that it corresponds to real time situation.",
            "Transmission capacity to be given to intraday market FI-EE",
            "Transmission capacity to be given to intraday market FI-EE. After Elspot trades have been closed, real time intraday capacity is equivalent to the allocated intraday capacity. The real time capacity is updated after each intraday trade so that it corresponds to real time situation.",
            "The capacity given to intraday market means transfer capacity after day-ahead trade from Finland (FI) to Russia (RUS). The indraday capacity between Finland and Russia is updated once a day. The data will not be revised after hourly day-ahead trade.",
            "Transmission capacity for intraday market from Finland to Northern Sweden (FI - SE1). For intraday market capacity is given as free capacity after dayahead market. Capacity is published once a day and not updated.",
            "Transmission capacity for intraday market from Finland to Mid Sweden (FI - SE3). For intraday market capacity is given as free capacity after dayahead market. Capacity is published once a day and not updated.",
            "The capacity given to intraday market means transfer capacity after day-ahead trade from Russia to Finland. The intraday capacity between Finland and Russia is updated once a day. The data will not be revised after hourly day-ahead trade.",
            "Transmission capacity for intraday market from Northern Sweden to Finland (SE1-FI). For intraday market capacity is given as free capacity after dayahead market. Capacity is published once a day and not updated.",
            "Transmission capacity for intraday market from Mid Sweden to Finland (SE3-FI). Capacity for intraday market  is given as free capacity after dayahead market. Capacity is published once a day and not updated.",
            "Real-time estimate of the kinetic energy of the Nordic power system calculated by the Nordic transmission system operators. The data is updated every 1 minute. Historical data as of 2015/3/27 available. More information can be found on Fingrid's internet-site.",
            "Measured electricity flow in North-South cut in Finland (cut P1). In the graph flow from North to South is positive.",
            "Net import to Finland and net export from Finland. The data is updated every 3 minutes. Production information and import/export are based on the real-time measurements in Fingrid's operation control system.",
            "Nuclear power production in Finland based on the real-time measurements in Fingrid's operation control system. The data is updated every 3 minutes. Due to the fire on our Olkiluoto substation the total amount of nuclear power measurement has been incorrect between 18 July at 09:00 to 20 July at 13:00. Data corrected 25.1.2019.",
            "Ordered down-regulations from Balancing energy market in Finland. The volume of ordered down-regulations from Balancing energy market in Finland is published hourly with two hours delay, eg. information from hour 06-07 is published at 9 o'clock. Balancing energy market is market place for manual freqeuncy restoration reserve (mFRR) which is used to balance the electricity generation and consumption in real time. The Balancing energy market organized by Fingrid is part of the Nordic Balancing energy market that is called also Regulating power market. Fingrid orders up- or down-regulation from the Balancing energy market. Down-regulation considers increasing of consumption or reducing of generation. Down-regulation volume has negative sign.",
            "Ordered up-regulations from Balancing energy market in Finland. The volume of ordered up-regulations from Balancing energy market in Finland is published hourly with two hours delay, eg. information from hour 06-07 is published at 9 o'clock. Balancing energy market is market place for manual freqeuncy restoration reserve (mFRR) which is used to balance the electricity generation and consumption in real time. The Balancing energy market organized by Fingrid is part of the Nordic Balancing energy market that is called also Regulating power market. Fingrid orders up- or down-regulation from the Balancing energy market. Up-regulation considers increasing of generation or reducing of consumption.",
            "Other power transactions which are necessary in view of the power system.",
            "Other power transactions which are necessary in view of the power system.",
            "Activated peak load power based on the real-time measurements in Fingrid's operation control system including peak load reserve activations and trial runs during winter period. The data is updated every 3 minutes.",
            "Planned transmission capacity from Finland to Russia. Transmission capacity is given hourly for every next week hour. Each week's hour is given one value. Planned weekly transmission capacity Fingrid will publish every Tuesday. Transmission capacity mean the capability of the electricity system to supply electricity to the market without compromising the system security.",
            "Planned transmission capacity from Russia to Finland. Transmission capacity is given hourly for every next week hour. Each week's hour is given one value. Planned weekly transmission capacity Fingrid will publish every Tuesday. Transmission capacity mean the capability of the electricity system to supply electricity to the market without compromising the system security.",
            "Planned weekly capacity on North-South cut in Finland (cut P1) from North to South. Planned outages are included in the weekly capacity, information is not updated after disturbances.",
            "Planned weekly capacity on North-South cut in Finland (cut P1) from South to North. Planned outages are included in the weekly capacity, information is not updated after disturbances.",
            "Different states of the power system - traffic lights: 1=green, 2=yellow, 3=red, 4=black, 5=blue Green: Power system is in normal secure state. Yellow: Power system is in endangered state. The adequacy of the electricity is endangered or the power system doesn't fulfill the security standards. Red: Power system is in disturbed state. Load shedding has happened in order to keep the adequacy and security of the power system or there is a remarkable risk to a wide black out.  Black: An extremely serious disturbance or a wide black out in Finland. Blue: The network is being restored after an extremely serious disturbance or a wide blackout. The data is updated every 3 minutes.",
            "The price of the last activated up-regulation bid. The price is published real-time  when Finland is a separate regulation area.",
            "Hourly updated solar power generation forecast for the next 36 hours. Solar forecasts are based on weather forecasts and estimates of installed PV capacity and location in Finland. Total PV capacity is based on yearly capacity statistics from the Finnish energy authority and estimates on installation rate of new capacity. Location information is a very rough estimate based on Finnish distribution grid operators information.",
            "Solar power generation forecasts for the next day. Forecast is updated every day at 12 p.m. EET. Length of the forecast is 36 hours. Overlapping hours are overwrited. Solar forecasts are based on weather forecasts and estimates of installed PV capacity and location in Finland. Total PV capacity is based on yearly capacity statistics from the Finnish energy authority and estimates on installation rate of new capacity. Location information is a very rough estimate based on Finnish distribution grid operators information.",
            "Regulation which takes place in the regulating power market by Fingrid for reasons other than the needs of national balance management",
            "Regulation which takes place in the regulating power market by Fingrid for reasons other than the needs of national balance management",
            "The capacity on the 400 kV connection from Finland to Russia is reserved to direct trade of the following commercial day. Fingrid and the Russian parties, who have jointly agreed that the capacity is 140 MW in both directions, daily confirm the capacity.",
            "Direct trade volumes derive from freely placed bids in the Nordic day-ahead (Elspot) and intraday (Elbas) electricity markets. Information is updated once the day-ahead market results are public. Information on the intraday trade is updated before the operational hour.",
            "The capacity on the 400 kV connection from Russia to Finland is reserved to direct trade of the following commercial day. Fingrid and the Russian parties, who have jointly agreed that the capacity is 140 MW in both directions, daily confirm the capacity.",
            "Information is based on the real time measurements in Fingrid's power control system. Power deficit/surplus represents the balance between production and consumption in Finland, taking into account imports and exports. It is calculated as the difference between the measured net import/export and the confirmed net exchange program between Finland and the other Nordic countries. The cumulative production deficit/surplus is the hourly energy generated from the difference. Sign convention: production deficit -, surplus + The data is updated every 3 minutes.",
            "Outside air temperature measurement at Tammisto substation. The data is updated every 3 minutes.",
            "Outside air temperature measurement at Petäjävesi substation. The data is updated every 3 minutes.",
            "Outside air temperature measurement at Leväsuo substation. The data is updated every 3 minutes.",
            "Outside air temperature measurement at Valajaskoski substation. The data is updated every 3 minutes.",
            "The hourly sum of the down-regulation offers given by Finnish parties to the Balancing energy market is published hourly with one hour delay, eg. information from hour 07-08 is published at 9 o'clock. Balancing energy market is market place for manual freqeuncy restoration reserve (mFRR) which is used to balance the electricity generation and consumption in real time. The Balancing energy market organized by Fingrid is part of the Nordic Balancing energy market that is called also Regulating power market. Fingrid orders up- or down-regulation from the Balancing energy market. Down-regulation considers increasing of consumption or reducing of generation. Down-regulation bids have negative sign.",
            "The hourly sum of the up-regulation offers given by Finnish parties to the Balancing energy market is published hourly with one hour delay, eg. information from hour 07-08 is published at 9 o'clock. Balancing energy market is market place for manual freqeuncy restoration reserve (mFRR) which is used to balance the electricity generation and consumption in real time. The Balancing energy market organized by Fingrid is part of the Nordic Balancing energy market that is called also Regulating power market. Fingrid orders up- or down-regulation from the Balancing energy market. Up-regulation considers increasing of production or reducing of consumption.",
            "Time deviation is the time difference in seconds between a clock running according to the frequency of the grid and a reference clock independent of the frequency of the grid. The data is updated every 3 minutes.",
            "This is the total solar power production capacity used in Fingrid's solar power forecast. It is based on the small scale production statistics gathered by the Energy authority. It is also updated with estimates based on information that's provided to Fingrid. This total capacity information can be used, for example, to calculate the rate of production of solar power, by comparing it to the forecasted solar production series by Fingrid. This capacity information cannot however be considered as the official amount of solar production capacity in Finland, as it is updated manually and by using estimates.",
            "This is the total wind production capacity used in Fingrid's wind power forecast. It is based capacity information gathered by Fingrid. This total capacity information can be used, for example, to calculate the rate of production of wind power, by comparing it to the actual wind production series by Fingrid. This capacity information cannot however be considered as the official amount of wind production capacity in Finland, as it is updated manually.",
            "Power transmission between Central Sweden (SE3) and Finland (FI) HVDC tie lines. Data is based on the real-time measurements in Fingrid's operation control system. Positive sign means transmission from Finland to Central Sweden (SE3). Negative sign means transmission from Central Sweden (SE3) to Finland. The data is updated every 3 minutes.",
            "Power transmission between Finland and Estonia HVDC tie lines (Estlink 1 and Estlink 2). Data is based on the real-time measurements in Fingrid's operation control system. Positive sign means transmission from Finland to Estonia. Negative sign means transmission from Estonia to Finland. The data is updated every 3 minutes.",
            "Power transmission between Northern Sweden (SE1) and Finland (FI) 400kV AC tie line. Data is based on the real-time measurements in Fingrid's operation control system. Positive sign means transmission from Finland to Northern Sweden (SE1). Negative sign means transmission from Northern Sweden (SE1) to Finland. The data is updated every 3 minutes.",
            "Power transmission between Finland and Norway 220kV AC tie line. Data is based on the real-time measurements in Fingrid's operation control system. Positive sign means transmission from Finland to Norway. Negative sign means transmission from Norway to Finland. The data is updated every 3 minutes.",
            "Power transmission between Finland and Russia based on the real-time measurements in Fingrid's operation control system. Positive sign means transmission from Finland to Russia. Negative sign means transmission from Russia to Finland. The data is updated every 3 minutes.",
            "Power transmission between Åland and Sweden based on the real-time measurements in Fingrid's operation control system. Åland is a part of SE3 (Central-Sweden) bidding zone. Positive sign means transmission from Åland to Sweden. Negative sign means transmission from Sweden to Åland. The data is updated every 3 minutes.",
            "The total commercial transmission capacity of the 400 kV transmission lines from Finland to Russia owned by Fingrid. The technical capacity on 400 kV lines from Russia to Finland is 1400 MW or 1000 MW, depending whether the NWPP power plant that is located in St. Petersburg area is connected to the Finnish or the Russian power system. Fingrid has reserved 100 MW of transmission capacity from Russia to Finland to buy reserve power. The technical maximum capacity from Finland to Russia is 350 MW, of which Fingrid has reserved 30 MW to buy reserve power.",
            "The total commercial transmission capacity of the 400 kV transmission lines from Russia to Finland owned by Fingrid. The technical capacity on 400 kV lines from Russia to Finland is 1400 MW or 1000 MW, depending whether the NWPP power plant that is located in St. Petersburg area is connected to the Finnish or the Russian power system. Fingrid has reserved 100 MW of transmission capacity from Russia to Finland to buy reserve power. The technical maximum capacity from Finland to Russia is 350 MW, of which Fingrid has reserved 30 MW to buy reserve power.",
            "Measured electrical transmission between Finland and Central Sweden (SE3) high voltage direct current tie lines. Positive sign means transmission from Finland to Central Sweden (SE3). Negative sign means transmission from Central Sweden (SE3) to Finland.  The value is updated once every hour after the hour shift. Each day before noon the values of the previous day are updated with more accurate measurement values.",
            "Measured electrical transmission between Finland and Estonia HVDC tile lines (Estlink 1 and Estlink 2). Positive sign means transmission from Finland to Estonia. Negative sign means transmission from Estonia to Finland.  The value is updated once every hour after the hour shift. Each day before noon the values of the previous day are updated with more accurate measurement values.",
            "Measured transmission of electricity between Finland and Northern Sweden (SE1).  Positive sign means transmission from Finland to Northern Sweden (SE1). Negative sign means transmission from Northern Sweden (SE1) to Finland.  The value is updated once every hour after the hour shift. Each day before noon the values of the previous day are updated with more accurate measurement values.",
            "Measured electrical transmission between Finland and Norway 220kV tie line.  Positive sign means transmission from Finland to Norway. Negative sign means transmission from Norway to Finland.  The value is updated once every hour after the hour shift. Each day before noon the values of the previous day are updated with more accurate measurement values.",
            "Measured electrical transmission between Finland and Russia.  Positive sign means transmission from Finland to Russia. Negative sign means transmission from Russia to Finland.  The value is updated once every hour after the hour shift. Each day before noon the values of the previous day are updated with more accurate measurement values.",
            "Measured electrical transmission between Finland and Åland islands DC tie line. Positive sign means transmission from Finland to Åland. Negative sign means transmission from Åland to Finland. The value is updated once a day before noon with the values of the previous day.",
            "Up-regulating price in Finland is the price of the most expensive up-regulating bid used in the Balancing energy market during the hour in question; however, it is at least the day ahead market price for the price area Finland. Up-regulating price for each hour is published hourly with one hour delay, eg. information from hour 07-08 is published at 9 o'clock. Balancing energy market is market place for manual freqeuncy restoration reserve (mFRR) which is used to balance the electricity generation and consumption in real time. The Balancing energy market organized by Fingrid is part of the Nordic Balancing energy market that is called also Regulating power market. Fingrid orders up- or down-regulation from the Balancing energy market. Up-regulation considers increasing of production or reducing of consumption.",
            "Value of Avoided Activation (VoAA) DK1 More information about VoAA and IC can be found in eSett Handbook (definitions and calculation rules). In case VoAA and IC cannot be calculated according to the set rules, the value 99 999 will be displayed for both.",
            "Value of Avoided Activation (VoAA) DK2 More information about VoAA and IC can be found in eSett Handbook (definitions and calculation rules).  In case VoAA and IC cannot be calculated according to the set rules, the value 99 999 will be displayed for both.",
            "Value of Avoided Activation (VoAA) FI More information about VoAA and IC can be found in eSett Handbook (definitions and calculation rules).  In case VoAA and IC cannot be calculated according to the set rules, the value 99 999 will be displayed for both.",
            "Value of Avoided Activation (VoAA) NO1 More information about VoAA and IC can be found in eSett Handbook (definitions and calculation rules). VoAA and IC are not implemented in Norway as in the other Nordic countries, but corresponding values are published for informational purposes. In case VoAA and IC cannot be calculated according to the set rules, the value 99 999 will be displayed for both.",
            "Value of Avoided Activation (VoAA) NO2 More information about VoAA and IC can be found in eSett Handbook (definitions and calculation rules). VoAA and IC are not implemented in Norway as in the other Nordic countries, but corresponding values are published for informational purposes. In case VoAA and IC cannot be calculated according to the set rules, the value 99 999 will be displayed for both.",
            "Value of Avoided Activation (VoAA) NO3 More information about VoAA and IC can be found in eSett Handbook (definitions and calculation rules). VoAA and IC are not implemented in Norway as in the other Nordic countries, but corresponding values are published for informational purposes. In case VoAA and IC cannot be calculated according to the set rules, the value 99 999 will be displayed for both.",
            "Value of Avoided Activation (VoAA) NO4 More information about VoAA and IC can be found in eSett Handbook (definitions and calculation rules). VoAA and IC are not implemented in Norway as in the other Nordic countries, but corresponding values are published for informational purposes. In case VoAA and IC cannot be calculated according to the set rules, the value 99 999 will be displayed for both.",
            "Value of Avoided Activation (VoAA) NO5 More information about VoAA and IC can be found in eSett Handbook (definitions and calculation rules). VoAA and IC are not implemented in Norway as in the other Nordic countries, but corresponding values are published for informational purposes.In case VoAA and IC cannot be calculated according to the set rules, the value 99 999 will be displayed for both.",
            "Value of Avoided Activation (VoAA) SE1 More information about VoAA and IC can be found in eSett Handbook (definitions and calculation rules). In case VoAA and IC cannot be calculated according to the set rules, the value 99 999 will be displayed for both.",
            "Value of Avoided Activation (VoAA) SE3 More information about VoAA and IC can be found in eSett Handbook (definitions and calculation rules). In case VoAA and IC cannot be calculated according to the set rules, the value 99 999 will be displayed for both.",
            "Value of Avoided Activation (VoAA) SE4 More information about VoAA and IC can be found in eSett Handbook (definitions and calculation rules). In case VoAA and IC cannot be calculated according to the set rules, the value 99 999 will be displayed for both.",
            "Finnish wind power generation forecast for the next 36 hours. Updated hourly.  The forecast is based on weather forecasts and data about the location, size and capacity of wind turbines. The weather data sourced from multiple providers.",
            "Finnish wind power generation forecasts for the next day. Forecast is updated every day at 12 p.m. EET. Length of the forecast is 36 hours. Overlapping hours are overwritten. The forecast is based on weather forecasts and data about the location, size and capacity of wind turbines. The weather data sourced from multiple providers.",
            "Finnish hourly wind power generation is a sum of measurements from wind parks supplied to Fingrid and of the estimate Fingrid makes from non-measured wind parks. Non-measured wind parks are about two percent of the production capacity.",
            "Wind power production based on the real-time measurements in Fingrid's operation control system. About two percent of the production capacity is estimated as measurements aren't available. The data is updated every 3 minutes.",
        ]
    }


